import type {
  BusinessArchitecturePreset,
  ServiceType,
} from '../types/service';

export const BUSINESS_ARCHITECTURE: Record<ServiceType, BusinessArchitecturePreset> = {
  freelancer: {
    status: 'activo',
    audience: 'Independientes y profesionales.',
    keyModuleKeys: ['ingresos', 'gastos', 'cobros', 'analizador-ia', 'impuestos-estimados'],
    languageTone: 'freelancer',
    dashboardExperience: 'Panel enfocado en ingresos, gastos, cobros pendientes, IA e impuestos estimados.',
    operationalFlows: ['Registrar ingresos', 'Registrar gastos', 'Seguir cobros pendientes', 'Estimar impuestos'],
  },
  servicios_profesionales: {
    status: 'disponible',
    audience: 'Agencias, estudios, productoras, consultores.',
    keyModuleKeys: ['proyectos', 'horas', 'propuestas', 'facturacion-servicio', 'rentabilidad-cliente'],
    languageTone: 'corporativo',
    dashboardExperience: 'Dashboard comercial con proyectos, horas, propuestas, facturación por servicio y rentabilidad por cliente.',
    operationalFlows: ['Crear propuesta', 'Abrir proyecto', 'Registrar horas', 'Facturar por servicio'],
  },
  sifen_empresarial: {
    status: 'disponible',
    audience: 'Empresas que emiten electrónicamente en Paraguay.',
    keyModuleKeys: ['facturacion-electronica', 'estados-dte', 'validacion', 'historial-tributario'],
    languageTone: 'tributario',
    dashboardExperience: 'Vista fiscal con facturación electrónica, estados DTE, validación e historial tributario.',
    operationalFlows: ['Emitir DTE', 'Validar documento', 'Revisar estados DTE', 'Consultar historial tributario'],
  },
  facturacion_autoimpresor: {
    status: 'disponible',
    audience: 'Negocios autorizados a imprimir sus comprobantes (Rangos y Timbrado).',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'asistido',
    dashboardExperience: 'Gestión de autoimpresores con control de timbrados, rangos numéricos y reporte de libros.',
    operationalFlows: ['Cargar timbrado', 'Controlar rangos', 'Emitir factura', 'Generar libro ventas'],
  },
  distribucion_flota: {
    status: 'disponible',
    audience: 'Distribuidores con vehículos propios o alquilados.',
    keyModuleKeys: ['vehiculos', 'rutas', 'combustible', 'mantenimiento', 'alquileres', 'costo-unidad'],
    languageTone: 'operativo',
    dashboardExperience: 'Control de vehículos, rutas, combustible, mantenimiento, alquileres y costo por unidad.',
    operationalFlows: ['Asignar vehiculo', 'Planificar ruta', 'Registrar combustible', 'Controlar mantenimiento'],
  },
  comercio_minorista: {
    status: 'disponible',
    audience: 'Tiendas y pequeños comercios.',
    keyModuleKeys: ['ventas', 'compras', 'inventario', 'caja-diaria', 'cuentas-por-cobrar-pagar'],
    languageTone: 'retail',
    dashboardExperience: 'Vista de ventas, compras, inventario, caja diaria y cuentas por cobrar/pagar.',
    operationalFlows: ['Registrar venta', 'Registrar compra', 'Actualizar inventario', 'Cerrar caja diaria'],
  },
  multiempresa: {
    status: 'disponible',
    audience: 'Grupos con varias razones sociales o unidades.',
    keyModuleKeys: ['consolidado', 'reportes-entidad', 'permisos-empresa'],
    languageTone: 'multiempresa',
    dashboardExperience: 'Experiencia multi-entidad con consolidado, reportes por entidad y permisos por empresa.',
    operationalFlows: ['Seleccionar entidad', 'Revisar consolidado', 'Comparar reportes', 'Gestionar permisos'],
  },
  // --- Backward compatibility / Niche types ---
  audiovisual: {
    status: 'disponible',
    audience: 'Productoras que gestionan proyectos audiovisuales y equipos.',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'audiovisual',
    dashboardExperience: 'Panel de producciones activas, rentabilidad por rodaje y control de equipos.',
    operationalFlows: ['Crear produccion', 'Asignar equipo', 'Registrar costo por rodaje', 'Facturar proyecto'],
  },
  salud: {
    status: 'disponible',
    audience: 'Servicios de salud con facturación IVA 5%.',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'salud',
    dashboardExperience: 'Vista asistencial con cobros, honorarios y control de IVA 5%.',
    operationalFlows: ['Registrar consulta', 'Emitir comprobante', 'Gestionar cobro', 'Controlar IVA 5%'],
  },
  educacion: {
    status: 'disponible',
    audience: 'Academias e institutos con cuotas mensuales.',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'educacion',
    dashboardExperience: 'Panel de cuotas, mora, agenda académica y caja operativa.',
    operationalFlows: ['Registrar alumno', 'Emitir cuota', 'Gestionar cobro', 'Revisar mora mensual'],
  },
  logistica: {
    status: 'disponible',
    audience: 'Operadores logísticos.',
    keyModuleKeys: ['vehiculos', 'rutas', 'costo-unidad'],
    languageTone: 'operativo',
    dashboardExperience: 'Seguimiento de operaciones logístico-financieras.',
    operationalFlows: ['Crear operacion', 'Asignar recurso', 'Registrar costo', 'Controlar rentabilidad'],
  },
};
