import type {
  BusinessArchitecturePreset,
  ServiceType,
} from '../types/service';

export const BUSINESS_ARCHITECTURE: Record<ServiceType, BusinessArchitecturePreset> = {
  freelancer: {
    status: 'activo',
    audience: 'Independientes y profesionales.',
    keyModuleKeys: ['ingresos', 'gastos', 'cobros', 'analizador-ia', 'impuestos-estimados'],
    languageTone: 'freelancer',
    dashboardExperience: 'Panel enfocado en caja, gastos deducibles, cobros pendientes e impuesto estimado.',
    operationalFlows: ['Registrar ingresos', 'Registrar gastos', 'Seguir cobros pendientes', 'Estimar impuestos'],
  },
  servicios_profesionales: {
    status: 'disponible',
    audience: 'Agencias, estudios, productoras y consultores.',
    keyModuleKeys: ['proyectos', 'horas', 'propuestas', 'facturacion-servicio', 'rentabilidad-cliente'],
    languageTone: 'corporativo',
    dashboardExperience: 'Dashboard comercial con rentabilidad por cliente, pipeline y control por proyecto.',
    operationalFlows: ['Crear propuesta', 'Abrir proyecto', 'Registrar horas', 'Facturar por servicio'],
  },
  sifen_empresarial: {
    status: 'disponible',
    audience: 'Empresas que emiten electronicamente en Paraguay.',
    keyModuleKeys: ['facturacion-electronica', 'estados-dte', 'validacion', 'historial-tributario'],
    languageTone: 'tributario',
    dashboardExperience: 'Vista fiscal con documentos emitidos, estados DTE, validaciones y salud tributaria.',
    operationalFlows: ['Emitir DTE', 'Validar documento', 'Revisar estados DTE', 'Consultar historial tributario'],
  },
  autofactura_guiada: {
    status: 'disponible',
    audience: 'Flujo restringido y asistido para emitir autofacturas con validacion previa y respaldo documental obligatorio.',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'asistido',
    dashboardExperience: 'Experiencia guiada y restringida con foco en checklist, respaldo y cumplimiento.',
    operationalFlows: ['Cargar respaldo', 'Validar checklist', 'Emitir autofactura', 'Controlar cobro'],
  },
  distribucion_flota: {
    status: 'disponible',
    audience: 'Distribuidores con vehiculos propios o alquilados.',
    keyModuleKeys: ['vehiculos', 'rutas', 'combustible', 'mantenimiento', 'alquileres', 'costo-unidad'],
    languageTone: 'operativo',
    dashboardExperience: 'Control operativo de flota, costo por ruta y alertas de mantenimiento.',
    operationalFlows: ['Asignar vehiculo', 'Planificar ruta', 'Registrar combustible', 'Controlar mantenimiento'],
  },
  comercio_minorista: {
    status: 'disponible',
    audience: 'Tiendas y pequenos comercios.',
    keyModuleKeys: ['ventas', 'compras', 'inventario', 'caja-diaria', 'cuentas-por-cobrar-pagar'],
    languageTone: 'retail',
    dashboardExperience: 'Vista de caja diaria, stock, ventas y saldos pendientes.',
    operationalFlows: ['Registrar venta', 'Registrar compra', 'Actualizar inventario', 'Cerrar caja diaria'],
  },
  multiempresa: {
    status: 'disponible',
    audience: 'Grupos con varias razones sociales o unidades.',
    keyModuleKeys: ['consolidado', 'reportes-entidad', 'permisos-empresa'],
    languageTone: 'multiempresa',
    dashboardExperience: 'Experiencia consolidada con comparativos por entidad y permisos por empresa.',
    operationalFlows: ['Seleccionar entidad', 'Revisar consolidado', 'Comparar reportes', 'Gestionar permisos'],
  },
  audiovisual: {
    status: 'disponible',
    audience: 'Productoras que gestionan proyectos audiovisuales, equipos y servicios de produccion.',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'audiovisual',
    dashboardExperience: 'Panel de producciones activas, rentabilidad por rodaje y control de equipos.',
    operationalFlows: ['Crear produccion', 'Asignar equipo', 'Registrar costo por rodaje', 'Facturar proyecto'],
  },
  salud: {
    status: 'disponible',
    audience: 'Clinicas, consultorios y profesionales de salud con facturacion IVA 5%.',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'salud',
    dashboardExperience: 'Vista asistencial con cobros, honorarios y control de IVA 5%.',
    operationalFlows: ['Registrar consulta', 'Emitir comprobante', 'Gestionar cobro', 'Controlar IVA 5%'],
  },
  educacion: {
    status: 'disponible',
    audience: 'Academias, institutos y docentes particulares con cobros de cuotas mensuales.',
    keyModuleKeys: ['dashboard', 'gastos', 'ingresos', 'cobros', 'reportes'],
    languageTone: 'educacion',
    dashboardExperience: 'Panel de cuotas, mora, agenda academica y caja operativa.',
    operationalFlows: ['Registrar alumno', 'Emitir cuota', 'Gestionar cobro', 'Revisar mora mensual'],
  },
  logistica: {
    status: 'disponible',
    audience: 'Operadores logisticos con control operativo y financiero.',
    keyModuleKeys: ['vehiculos', 'rutas', 'combustible', 'mantenimiento', 'costo-unidad'],
    languageTone: 'operativo',
    dashboardExperience: 'Seguimiento de operaciones logistico-financieras.',
    operationalFlows: ['Crear operacion', 'Asignar recurso', 'Registrar costo', 'Controlar rentabilidad'],
  },
};
