import type { ServiceModuleDefinition, ServiceModuleKey } from '../types/service';

export const SERVICE_MODULE_CATALOG: Record<ServiceModuleKey, ServiceModuleDefinition> = {
  dashboard: {
    key: 'dashboard',
    label: 'Dashboard',
    description: 'Vista principal con KPIs, alertas y resumen operativo.',
    category: 'core',
    availability: 'implemented',
    configurable: true,
    path: '/dashboard',
  },
  'analizador-ia': {
    key: 'analizador-ia',
    label: 'Analizador IA',
    description: 'Centro para carga inteligente de ingresos y gastos.',
    category: 'core',
    availability: 'implemented',
    configurable: true,
    path: '/analizador-ia/gastos',
  },
  gastos: {
    key: 'gastos',
    label: 'Gastos',
    description: 'Registro y clasificacion de egresos.',
    category: 'finance',
    availability: 'implemented',
    configurable: true,
    path: '/analizador-ia/gastos',
  },
  ingresos: {
    key: 'ingresos',
    label: 'Ingresos',
    description: 'Registro de ventas, facturas y cobros emitidos.',
    category: 'finance',
    availability: 'implemented',
    configurable: true,
    path: '/analizador-ia/ingresos',
  },
  'gestion-freelancer': {
    key: 'gestion-freelancer',
    label: 'Gestion Freelancer',
    description: 'Bloque operativo orientado a profesionales independientes.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
  },
  cobros: {
    key: 'cobros',
    label: 'Cobros',
    description: 'Seguimiento de cuentas pendientes y recuperacion.',
    category: 'finance',
    availability: 'implemented',
    configurable: true,
    path: '/centro-cobros',
  },
  agenda: {
    key: 'agenda',
    label: 'Agenda',
    description: 'Agenda de vencimientos, tareas y compromisos.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
    path: '/agenda',
  },
  planificacion: {
    key: 'planificacion',
    label: 'Disponibilidad',
    description: 'Planificacion operativa y disponibilidad del equipo.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
    path: '/planificacion',
  },
  set: {
    key: 'set',
    label: 'Asistente SET',
    description: 'Apoyo fiscal para declaraciones y control mensual.',
    category: 'fiscal',
    availability: 'implemented',
    configurable: true,
    path: '/asistente-set',
  },
  conciliacion: {
    key: 'conciliacion',
    label: 'Conciliacion',
    description: 'Cruce de movimientos bancarios y fiscales.',
    category: 'fiscal',
    availability: 'implemented',
    configurable: true,
    path: '/fiscal/conciliacion',
  },
  cierre: {
    key: 'cierre',
    label: 'Cierre Mensual',
    description: 'Proceso guiado de cierre operativo y fiscal.',
    category: 'fiscal',
    availability: 'implemented',
    configurable: true,
    path: '/fiscal/cierre',
  },
  sifen: {
    key: 'sifen',
    label: 'Perfil SIFEN',
    description: 'Facturacion electronica, configuracion y emision.',
    category: 'fiscal',
    availability: 'implemented',
    configurable: true,
    path: '/sifen',
  },
  clientes: {
    key: 'clientes',
    label: 'Clientes',
    description: 'Directorio comercial y receptores para facturacion.',
    category: 'crm',
    availability: 'implemented',
    configurable: true,
    path: '/sifen/clientes',
  },
  proyectos: {
    key: 'proyectos',
    label: 'Proyectos',
    description: 'Gestion de proyectos, contratos y entregables.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
    path: '/proyectos',
  },
  servicios: {
    key: 'servicios',
    label: 'Servicios',
    description: 'Centro de servicios, propuestas y ejecucion.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
    path: '/servicios',
  },
  inventario: {
    key: 'inventario',
    label: 'Inventario y Activos',
    description: 'Control de equipos, stock y activos operativos.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
    path: '/activos',
  },
  catalog: {
    key: 'catalog',
    label: 'Catalogo',
    description: 'Catalogo reusable de servicios o productos.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
    path: '/catalog',
  },
  facturas_virtuales: {
    key: 'facturas_virtuales',
    label: 'Facturacion Virtual',
    description: 'Registro de comprobantes autoimpresos y facturas virtuales SET.',
    category: 'fiscal',
    availability: 'implemented',
    configurable: true,
    path: '/facturacion-virtual',
  },
  productos_catalogo: {
    key: 'productos_catalogo',
    label: 'Catalogo de Productos',
    description: 'Gestion de productos, precios, stock y codigos de barras.',
    category: 'operations',
    availability: 'implemented',
    configurable: true,
    path: '/productos',
  },
  reportes: {
    key: 'reportes',
    label: 'Reportes',
    description: 'Analisis financiero y reportes ejecutivos.',
    category: 'analytics',
    availability: 'implemented',
    configurable: true,
    path: '/analisis',
  },
  settings: {
    key: 'settings',
    label: 'Configuracion',
    description: 'Parametros, marca, facturacion y backup.',
    category: 'core',
    availability: 'implemented',
    configurable: true,
    path: '/config',
  },
  admin: {
    key: 'admin',
    label: 'Admin',
    description: 'Gestion centralizada de clientes, perfiles y permisos.',
    category: 'core',
    availability: 'implemented',
    configurable: false,
    path: '/admin',
  },
  horas: {
    key: 'horas',
    label: 'Horas',
    description: 'Registro de horas imputables por proyecto o cliente.',
    category: 'operations',
    availability: 'planned',
    configurable: true,
  },
  propuestas: {
    key: 'propuestas',
    label: 'Propuestas',
    description: 'Generacion y seguimiento de propuestas comerciales.',
    category: 'operations',
    availability: 'planned',
    configurable: true,
  },
  'facturacion-servicio': {
    key: 'facturacion-servicio',
    label: 'Facturacion por Servicio',
    description: 'Facturacion vinculada a entregables, hitos o contratos.',
    category: 'finance',
    availability: 'planned',
    configurable: true,
  },
  'rentabilidad-cliente': {
    key: 'rentabilidad-cliente',
    label: 'Rentabilidad por Cliente',
    description: 'Margen y performance por cliente o contrato.',
    category: 'analytics',
    availability: 'planned',
    configurable: true,
  },
  'facturacion-electronica': {
    key: 'facturacion-electronica',
    label: 'Facturacion Electronica',
    description: 'Centro operativo de emision DTE.',
    category: 'fiscal',
    availability: 'planned',
    configurable: true,
  },
  'estados-dte': {
    key: 'estados-dte',
    label: 'Estados DTE',
    description: 'Seguimiento de aprobados, rechazados y anulados.',
    category: 'fiscal',
    availability: 'planned',
    configurable: true,
  },
  validacion: {
    key: 'validacion',
    label: 'Validacion',
    description: 'Validaciones previas y controles tributarios.',
    category: 'fiscal',
    availability: 'planned',
    configurable: true,
  },
  'historial-tributario': {
    key: 'historial-tributario',
    label: 'Historial Tributario',
    description: 'Historial de eventos, declaraciones y trazabilidad fiscal.',
    category: 'fiscal',
    availability: 'planned',
    configurable: true,
  },
  vehiculos: {
    key: 'vehiculos',
    label: 'Vehiculos',
    description: 'Gestion de vehiculos propios o alquilados.',
    category: 'operations',
    availability: 'planned',
    configurable: true,
  },
  rutas: {
    key: 'rutas',
    label: 'Rutas',
    description: 'Planificacion y control de rutas.',
    category: 'operations',
    availability: 'planned',
    configurable: true,
  },
  combustible: {
    key: 'combustible',
    label: 'Combustible',
    description: 'Control de consumo y costo por combustible.',
    category: 'operations',
    availability: 'planned',
    configurable: true,
  },
  mantenimiento: {
    key: 'mantenimiento',
    label: 'Mantenimiento',
    description: 'Mantenimientos preventivos y correctivos.',
    category: 'operations',
    availability: 'planned',
    configurable: true,
  },
  alquileres: {
    key: 'alquileres',
    label: 'Alquileres',
    description: 'Control de alquileres de flota o equipos.',
    category: 'operations',
    availability: 'planned',
    configurable: true,
  },
  'costo-unidad': {
    key: 'costo-unidad',
    label: 'Costo por Unidad',
    description: 'Calculo de costos unitarios por ruta, unidad o pedido.',
    category: 'analytics',
    availability: 'planned',
    configurable: true,
  },
  ventas: {
    key: 'ventas',
    label: 'Ventas',
    description: 'Centro de ventas y tickets.',
    category: 'finance',
    availability: 'planned',
    configurable: true,
  },
  compras: {
    key: 'compras',
    label: 'Compras',
    description: 'Registro de compras y proveedores.',
    category: 'finance',
    availability: 'planned',
    configurable: true,
  },
  'caja-diaria': {
    key: 'caja-diaria',
    label: 'Caja Diaria',
    description: 'Arqueo y cierre diario de caja.',
    category: 'finance',
    availability: 'planned',
    configurable: true,
  },
  'cuentas-por-cobrar-pagar': {
    key: 'cuentas-por-cobrar-pagar',
    label: 'Cuentas por Cobrar/Pagar',
    description: 'Gestion consolidada de saldos pendientes.',
    category: 'finance',
    availability: 'planned',
    configurable: true,
  },
  consolidado: {
    key: 'consolidado',
    label: 'Consolidado',
    description: 'Vista consolidada multiempresa.',
    category: 'analytics',
    availability: 'planned',
    configurable: true,
  },
  'reportes-entidad': {
    key: 'reportes-entidad',
    label: 'Reportes por Entidad',
    description: 'Comparativos y cierres por razon social.',
    category: 'analytics',
    availability: 'planned',
    configurable: true,
  },
  'permisos-empresa': {
    key: 'permisos-empresa',
    label: 'Permisos por Empresa',
    description: 'Asignacion granular de acceso por entidad.',
    category: 'core',
    availability: 'planned',
    configurable: true,
  },
  'impuestos-estimados': {
    key: 'impuestos-estimados',
    label: 'Impuestos Estimados',
    description: 'Estimacion tributaria por periodo.',
    category: 'fiscal',
    availability: 'planned',
    configurable: true,
  },
};

export const RUNTIME_EDITABLE_MODULES = Object.values(SERVICE_MODULE_CATALOG).filter(
  (moduleDef) => moduleDef.configurable && moduleDef.availability === 'implemented'
);

export function getModuleDefinition(moduleKey: string) {
  return SERVICE_MODULE_CATALOG[moduleKey as ServiceModuleKey];
}

export function getModuleLabel(moduleKey: string) {
  return getModuleDefinition(moduleKey)?.label || moduleKey;
}
